### ISSUE TITLE
online demo please :)?

### ISSUE THREAD

**Issue by winkler1** [Schniz/react-gooey-nav#1]
Would like to add to react.rocks -- thanks!

**Comment by Schniz** [comment]
now available (and hideous) @ http://schniz.github.io/react-gooey-nav/

**Comment by Schniz** [comment]
oh yeah @winkler1, thank you for your interest! :sweat_smile:

**Comment by winkler1** [comment]
Sure :) Is this how it should look? The blobs are empty for me, seems like that doesn't really get the point across. Thanks!

![image](https://cloud.githubusercontent.com/assets/883896/6426954/a1a70158-bf3f-11e4-9a20-1c7da6947baf.png)

**Comment by Schniz** [comment]
that's weird. can you check if you can react the font awesome CDN? is there any error in the console?

**Comment by winkler1** [comment]
Yup, somehow uBlock was blocking the fonts. thanks.
