### ISSUE TITLE
React Router Links?

### ISSUE THREAD

**Issue by Schniz** [Schniz/react-gooey-nav#2]
how to address this?

**Comment by Jromero97** [comment]
Somebody know more about this?

**Comment by Schniz** [comment]
Hey there, 3 years has passed since I wrote this component. It can probably be written better now (and we can lower the boilerplate by using `microbundle` or `parcel`. I will try to allocate time for this over the weekend

**Comment by Jromero97** [comment]
Hey! I hope you can do this better than it is, its beautiful and brings elegance to the page. I'll be waiting for an update! ;)

**Comment by Schniz** [comment]
Well, now it supports any component, including React Router `Link`s 🎉
