### ISSUE TITLE
Nav Height issue

### ISSUE THREAD

**Issue by Dinushasilva** [Schniz/react-gooey-nav#3]
in your example Make sure the nav height is 270px; or it should be 100% if you have more links :) @Schniz.. :+1: 

![schniz github io react gooey navb](https://cloud.githubusercontent.com/assets/11263156/6434377/970f7fee-c0ad-11e4-9110-ce17d10cf33d.png) - Before

![schniz github io react gooey nav](https://cloud.githubusercontent.com/assets/11263156/6434386/b5a1dd4e-c0ad-11e4-8981-4891ef011d3a.png) - After

**Comment by Schniz** [comment]
hey @Dinushasilva, I've added one more logo to check it out and I can't see any difference in my computer.
Can you post the pictures now? and maybe change the source yourself? :smile:
http://schniz.github.io/react-gooey-nav/

**Comment by Dinushasilva** [comment]
It is the same bro..look

![schniz github io react gooey nav](https://cloud.githubusercontent.com/assets/11263156/6464876/4c26c780-c1e3-11e4-894f-5f27e89b8331.png) -see the edge it is not smooth since the nav height is too small 

![schniz github io react gooey navb](https://cloud.githubusercontent.com/assets/11263156/6464904/75d4f3cc-c1e3-11e4-9c82-b9a99b81a491.png) -after It is smooth now :) :+1: 

@Schniz Hey jus check the nav height which is 150 is too small..

**Comment by Schniz** [comment]
I think it is fixed. I'm closing for now 😳 
Thanks @Dinushasilva for contributing the issue though, I think I fixed it after you told me to ;p
