### ISSUE TITLE
Doesn't work with react app

### ISSUE THREAD

**Issue by sjollois** [Schniz/react-gooey-nav#6]
Hello, 

It doesn't work when I try do implement it in my React app 

![capture d ecran 2018-02-12 a 16 38 26](https://user-images.githubusercontent.com/23353046/36104779-34fee44e-1013-11e8-9db9-4e7c7d543465.png)

Thank you very much for your support!!

**Comment by Schniz** [comment]
hey friend.
this library isn't maintained, I did it for fun 3 years ago. Sorry! 🤷‍♂️  
However! There's a slight chance that https://github.com/facebook/create-react-app/issues/1125 will solve this.

You can also send a PR: we should have a `build` script to generate compiled js files into `dist/` or something of some sort. what do you say?

**Comment by Schniz** [comment]
Hey @sjollois, thanks for your issue and sorry for the inconvenience. as I mentioned in #2, I'll try to allocate some time to work on it over the weekend to fix it. It should work for CRA too after some fixes. Fingers crossed!

**Comment by Schniz** [comment]
Hey there @sjollois. I would like to have your feedback about the new release!

**Comment by Schniz** [comment]
Closed due to inactivity
