### ISSUE TITLE
how to run your code 

### ISSUE THREAD

**Issue by KPSoftec** [Schniz/react-gooey-nav#7]
I can do some good changes in this if you help me to setup this code.
How to run this code.

**Comment by Schniz** [comment]
Hey @KPSoftec, sorry for my late response! Thanks for your interest!
as I said in #2, I'll try to allocate time this weekend to rewrite and use modern tools so it would be easier to use and comprehend. The state of React in 2018 is different than it was in 2015.
Would love to see contributions, though! so if you'd like to reimplement it on your own, I'm totally in 😸 

I'll try to make it compatible with CRA (and Parcel, etc 😄 )

**Comment by Schniz** [comment]
whoops, accidentally closed it

**Comment by Schniz** [comment]
Hey, @KPSoftec, please look at the master branch. I believe it is easier to use it now 😸 

Please let me know if I can make it better

**Comment by Schniz** [comment]
Closed due to inactivity
